name: pimouse ROS CI2

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: pimouse_run_2025
      - uses: actions/checkout@v3
        with:
          repository: githirade/pimouse2025
          path: pimouse_2025
      - name: Start container and mount both packages
        run: |
          docker run --name ros_ci_container -d \
            -v ${{ github.workspace }}/pimouse_2025:/root/pimouse_2025 \
            -v ${{ github.workspace }}/pimouse_run_2025:/root/pimouse_run_2025 \
            ros:melodic-ros-base-bionic tail -f /dev/null
          docker exec ros_ci_container bash -c "
            apt update
            apt install -y sudo python3-pip build-essential \
                           ros-melodic-catkin ros-melodic-rostest \
                           python3-rosdep git xvfb && \
            rosdep init || true
            rosdep update
            source /opt/ros/melodic/setup.bash
            mkdir -p /root/catkin_ws/src
            ln -s /root/pimouse_2025 /root/catkin_ws/src/pimouse_2025
            ln -s /root/pimouse_run_2025 /root/catkin_ws/src/pimouse_run_2025
            cd /root/catkin_ws
            rosdep install --from-paths src --ignore-src -r -y
            catkin_make
          "
      - name: Create dummy /dev/rt* devices
        run: |
          docker exec ros_ci_container bash -c "
            source /opt/ros/melodic/setup.bash
            sudo touch /dev/rt{buzzer,motor,motoren,motor_raw_{l,r}}0
            sudo chmod 666 /dev/rt{buzzer,motor,motoren,motor_raw_{l,r}}0
            sudo bash -c 'echo \"0 0 0 0\" > /dev/rtlightsensor0'
            sudo chmod 666 /dev/rtlightsensor0
            sudo bash -c 'echo \"0\" > /dev/rtswitch0'
            sudo bash -c 'echo \"0\" > /dev/rtswitch1'
            sudo bash -c 'echo \"0\" > /dev/rtswitch2'
            sudo chmod 666 /dev/rtswitch{0,1,2}
          "
        
      - name: Run tests inside container
        run: |
          docker exec ros_ci_container bash -c "
            source /opt/ros/melodic/setup.bash
            source /root/catkin_ws/devel/setup.bash
            xvfb-run -a rostest pimouse_run_2025 wall_stop.launch
            xvfb-run -a rostest pimouse_run_2025 wall_stop_accel.launch
            xvfb-run -a rostest pimouse_run_2025 wall_trace.launch
            xvfb-run -a rostest pimouse_run_2025 wall_around.launch
          "

      - name: Cleanup
        if: always()
        run: docker rm -f ros_ci_container
